### ISSUE TITLE
Rig App: Create layout to handle rendering Pilot over Rig

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/rigs#205]

**Comment by joewagner** [comment]
I have an initial app that renders a fixed moonbird pilot on any rig here: https://github.com/tablelandnetwork/rigs/tree/joe/animation_url/animation_url
to play with it:
1. clone the rigs repo
2. cd into animation_url
3. npm install && npm run dev
4. open http://localhost:5173?rig=<any valid rig ID>

I used the layout shown in Figma as a starting place. Feedback would be great.
A few notes:
 - Eventually we will need to get the image url from a tableland query.
 - Any nft image will work, but the height is always going to be set at 20%.  This should work for most any nft, but if the aspect ratio is really wide, it might start to look strange.  If the aspect ratio of the pilot nft is more than 5 times wider than tall it will break the layout.
 -

**Comment by sanderpick** [comment]
Looking good! Couple notes:
- Badge fill should be #162929
- Badge padding should be 10px from top and left side of frame and 10px from each other

> Any nft image will work, but the height is always going to be set at 20%. This should work for most any nft, but if the aspect ratio is really wide, it might start to look strange. If the aspect ratio of the pilot nft is more than 5 times wider than tall it will break the layout.

Makes sense. We could also create a maximum width on the pilot. If the width max is reached, the height could start coming down below 20%.

**Comment by joewagner** [comment]
@sanderpick I just pushed some updates.  Badge fill is changed, and you can easily tinker with what it will look like when different numbers of badges are shown and different aspect ratio pilots are chosen.  
Couple notes:
- px based padding won't work how things are setup right now because the number of badges per row if fixed.  A fixed number of badges per row means we need padding to be percent based.  I set the padding to 0.7%, which is very close to 10px for average market place displays on computer or tablet screen sizes.  You can tinker with the number of badges a rig has [here](https://github.com/tablelandnetwork/rigs/blob/joe/animation_url/animation_url/src/routes/%2Bpage.ts#L44)
- I set the pilot to have a max height of 37% and max width of 25%.  You can tinker with this by changing the pilot image [here](https://github.com/tablelandnetwork/rigs/blob/joe/animation_url/animation_url/src/routes/%2Bpage.ts#L104)
- Different rigs have different padding, or lack of, from the badges and pilot.  rig 1, 5, 7, and 1106 are some good comparisons.

**Comment by sanderpick** [comment]
Nice! How about we say that badges go vertically on the left. If you have too many to display, you'd have to make a decision about which ones to showcase on your rig. This would work for rigs that have very little padding. eg,

<img width="58" alt="Screen Shot 2022-10-06 at 10 27 27 AM" src="https://user-images.githubusercontent.com/361000/194368143-191c68e2-6407-4cc8-86e2-2f6c997605ef.png">

**Comment by joewagner** [comment]
> Nice! How about we say that badges go vertically on the left. If you have too many to display, you'd have to make a decision about which ones to showcase on your rig. This would work for rigs that have very little padding. eg,

Sounds good to me!

**Comment by joewagner** [comment]
Ok, the latest updates to `joe/animation_url` have the new ipfs gateway and the badges on the left side with a max of 11 shown
